@startuml
'https://plantuml.com/class-diagram

class ListMaker {
    main()
    start()
}

class ListMakerController {
    createNewListClicked()
    editListClicked()
    autoGenerateListClicked()
}

ListMaker - ListMakerController
javafx.Application <|-- ListMaker

@enduml